language: python
python:
  - "3.8"
env:
  - KERAS_BACKEND=theano
cache: apt
addons:
  # It seems that this avoids problems with scipy
  # http://lmjohns3.com/2015/06/using-travis-ci-with-miniconda-scipy-and-nose.html
  apt:
    packages:
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda
install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION pip numpy scipy nose
  - pip install pep8 python-coveralls
  # Build/test dependencies
  - pip install -r requirements3.txt
  # Get fab to test fab
  - pip install -e .
# Command to run tests
script:
  # Run keras backend init to initialize backend config
  - python -c "import keras.backend"
  # Create dataset directory to avoid concurrent directory creation at runtime
  - mkdir ~/.keras/datasets
  # Set up keras backend
  - sed -i -e 's/"backend":[[:space:]]*"[^"]*/"backend":\ "'$KERAS_BACKEND'/g' ~/.keras/keras.json;
  # Normal tests
  - ./runtests.sh
after_success:
  - coveralls
